[package]
name = "broadside_net"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
from_variants = "1.0.2"
iroh = "0.91.2"
oneshot = "0.1.11"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["io-std", "macros", "sync"] }
